.\"-
.\" Copyright (c) 2026 REVYTECH, Inc.
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.\" This software was developed by REVYTECH, Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
.\" DAMAGE.
.\"
.Dd June 5, 2026
.Dt OCIFBSD_NETWORK 3
.Os
.Sh NAME
.Nm ocifbsd_network
.Nd ocifbsd networking library
.Sh SYNOPSIS
.In ocifbsd/network.h
.Ft int
.Fn network_init "void"
.Ft int
.Fn network_shutdown "void"
.Ft int
.Fn bridge_create "const char *name"
.Ft int
.Fn bridge_destroy "const char *name"
.Ft int
.Fn vnet_setup "int jid" "const char *ifname"
.Ft int
.Fn cni_load "const char *plugin_path"
.Ft int
.Fn cni_invoke "const char *container_id" "const char *netns"
.Sh DESCRIPTION
The
.Nm
library implements the networking primitives used by
.Xr ocifbsd 8
to attach containers and jails to the host network.
It is not a standalone program; it is linked into
the main
.Xr ocifbsd 8
binary and any external tooling that needs to
manage bridges, VNET interfaces, or CNI plugins.
.Pp
The library provides four functional areas:
.Bl -bullet
.It
Core network lifecycle
.Pq network.c
initialises and tears down the networking
subsystem and tracks active bridges and interfaces.
.It
Bridge management
.Pq bridge.c
creates and destroys
.Xr if_bridge 4
instances that connect container VNET
stacks to the host network.
.It
VNET support
.Pq vnet.c
attaches jails to a bridge and configures
their virtual network stack.
.It
CNI plugin loader
.Pq cni.c
loads and invokes
.Xr cni 7
plugins from the configured plugin search path,
passing the standard ADD, DEL, and CHECK operations
through to the plugin and returning its result.
.El
.Pp
The public API is declared in
.In ocifbsd/network.h ;
see the header for the full list of functions and
data structures.
.Sh FILES
.Bl -tag -width /usr/local/lib/cni -compact
.It Pa /usr/local/lib/cni
Default CNI plugin search path.
.It Pa /etc/ocifbsd/network.conf
Network configuration (bridge name, CIDR ranges, plugin path).
.El
.Sh SEE ALSO
.Xr ocifbsd 8 ,
.Xr cni 7 ,
.Xr if_bridge 4 ,
.Xr jail 8 ,
.Xr vnet 9
.Sh HISTORY
The
.Nm
library first appeared in
.Fx 16.0 .
.Sh AUTHORS
The
.Nm
library was developed by
.An REVYTECH, Inc.
