# $FreeBSD$
#
# Makefile for ocifbsd orchestration module
#

SRCS=	pod.c stack.c scheduler.c health.c rolling_update.c orch_cli.c orch_init.c

PROG=	ocifbsd_orch
MAN=

WARNS?=	3

.include <bsd.prog.mk>
