.\" Copyright (c) 2024 The FreeBSD Foundation
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
.\" THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
.\" DAMAGE.
.\"
.\" $FreeBSD$
.Dd April 30, 2026
.Dt OCIFBSD 8
.Os
.Sh NAME
.Nm ocifbsd
.Nd FreeBSD Native OCI Runtime
.Sh SYNOPSIS
.Nm
.Op Fl vhV
.Ar command
.Op Ar arguments
.Sh DESCRIPTION
.Nm
is the FreeBSD native OCI (Open Container Initiative) runtime that provides
container isolation using FreeBSD jails.
.Pp
The following commands are available:
.Bl -tag -width ".Cm run"
.It Cm create Ar bundle Op Fl n Ar name
Create a container from an OCI bundle.
.It Cm start Ar container-id
Start a created container.
.It Cm kill Ar container-id Op Fl s Ar signal
Send a signal to a running container.
The default signal is SIGTERM.
.It Cm delete Ar container-id Op Fl f
Delete a container.
Use
.Fl f
to force deletion of a running container.
.It Cm state Ar container-id
Show the current state of a container.
.It Cm list
List all containers.
.It Cm inspect Ar container-id
Show detailed information about a container.
.It Cm run Ar bundle Op Fl n Ar name
Create and start a container in one command.
.El
.Sh OPTIONS
.Bl -tag -width ".Fl v"
.It Fl v , -verbose
Enable verbose output.
.It Fl h , -help
Show help message and exit.
.It Fl V , -version
Show version information and exit.
.El
.Sh EXAMPLES
Create a container from an OCI bundle:
.Bd -literal
ocifbsd create /path/to/bundle --name my-container
.Ed
.Pp
Start the container:
.Bd -literal
ocifbsd start my-container-id
.Ed
.Pp
Create and run in one command:
.Bd -literal
ocifbsd run /path/to/bundle --name web
.Ed
.Pp
Delete a container:
.Bd -literal
ocifbsd delete my-container-id
.Ed
.Sh FILES
.Bl -tag -width ".Pa /var/run/ocifbsd" -compact
.It Pa /var/run/ocifbsd/
Runtime state directory
.It Pa /var/lib/ocifbsd/
Image and volume data directory
.It Pa /etc/ocifbsd/
Configuration directory
.El
.Sh SEE ALSO
.Xr jail 8 ,
.Xr jail 3
.Sh HISTORY
.Nm
was developed to provide native OCI runtime support for FreeBSD.
.Sh AUTHORS
.Nm
was developed by Klara, Inc. under sponsorship from the FreeBSD Foundation.
